version: "2.2"
services:
    elasticsearch1:
        image: elasticsearch:7.3.1
        container_name: elasticsearch1
        environment:
            - node.name=elasticsearch1
            - discovery.seed_hosts=elasticsearch2
            - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data      
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    elasticsearch2:
        image: elasticsearch:7.3.1
        container_name: elasticsearch2
        environment:
            - node.name=elasticsearch2
            - discovery.seed_hosts=elasticsearch1
            - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata2:/usr/share/elasticsearch/data
        networks:
            - elknetwork
    kibana:
        image: kibana:7.3.1
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch1:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch1:9200","http://elasticsearch2:9200"]'
        networks:
            - elknetwork
    logstash:
        image: logstash:7.3.1
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
            - .\logstash:/usr/share/logstash/pipeline/
        networks:
            - elknetwork
    headPlugin:
        image: 'mobz/elasticsearch-head:5'
        container_name: head
        ports:
            - '9100:9100'
networks:
    elknetwork:
        driver: bridge

volumes:
    esdata1:
        driver: local
    esdata2:
        driver: local
